name: Docker Image CD

on:
  workflow_dispatch:
 
env:
  IMAGE_NAME: doosyapii


jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Checkout code
      uses: actions/checkout@v2
    
    
    
    
      
      
    
        
        
    - name: USING ACTION TO BUILD AND PUST :)
      uses: NRO04/docker-build-push-action@v2
      with: #args for action, all of them are required.
          name-repository: ${{ github.repository }} #repository name, specify what the repository will be called on dockerhub.
          tag: v1 #tag for repository
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }} # docker account - username
          docker-password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      
    - name: image deigest
      run: echo ${{ steps.build.outputs.diegest }}
      
    - name: testing doosy-deploy ssh  connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [  "$(docker ps  -a -f status=running  -f  name=webapplications)" ]; then
            docker kill webapplications;
            docker rm webapplications;
            docker create --name webapplications  -p 5002:80 kekgaugetswe/webapplications:latest
            docker start webapplications
          fi
          docker ps -a
          
